CREATE DATABASE PCLINICS;
GO

USE PCLINICS
GO

CREATE TABLE DONO (
  idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
  nomeDono VARCHAR(50) NOT NULL
);
GO

CREATE TABLE TIPOPET (
  idTipoPet TINYINT PRIMARY KEY IDENTITY(1,1),
  nomeTipoPet VARCHAR(30) NOT NULL
);
GO

CREATE TABLE RACA (
  idRaca SMALLINT PRIMARY KEY IDENTITY(1,1),
  idTipoPet TINYINT FOREIGN KEY REFERENCES TIPOPET(idTipoPet),
  nomeRaca VARCHAR(30) NOT NULL
);
GO

CREATE TABLE PET (
  idPet SMALLINT PRIMARY KEY IDENTITY(1,1),
  idRaca SMALLINT FOREIGN KEY REFERENCES RACA(idRaca),
  idDono SMALLINT FOREIGN  KEY REFERENCES DONO(idDono),
  nomePet VARCHAR(25) NOT NULL,
  dataNascimentoPet DATE NOT NULL
);
GO

CREATE TABLE CLINICA (
  idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
  nomeClinica VARCHAR(30) NOT NULL,
  endereco VARCHAR(50) NOT NULL
);
GO

CREATE TABLE VETERINARIO (
  idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
  idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
  nomeVeterinario VARCHAR(50) NOT NULL
);
GO

CREATE TABLE ATENDIMENTO (
  idAtendimento INT PRIMARY KEY IDENTITY(1,1),
  idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario),
  idPet SMALLINT FOREIGN KEY REFERENCES PET(idPet),
  dataAtendimento DATE NOT NULL
);
GO
