CREATE DATABASE EMPRESA

USE EMPRESA;
GO

CREATE TABLE PESSOA (
  idPessoa SMALLINT PRIMARY KEY IDENTITY(1,1),
  nomePessoa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE TELEFONE (
  idTelefone SMALLINT PRIMARY KEY IDENTITY(1,1),
  idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
  numeroTelefone VARCHAR(15) NOT NULL
);
GO

CREATE TABLE EMAIL(
  idEmail INT PRIMARY KEY IDENTITY(1,1),
  idPessoa SMALLINT FOREIGN KEY REFERENCES PESSOA(idPessoa),
  the_email VARCHAR(256) NOT NULL
);
GO