CREATE DATABASE OPTUS;
GO

USE OPTUS
GO

CREATE TABLE USUARIO (
  idUsuario INT PRIMARY KEY IDENTITY(1,1), 
  nomeUsuario VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  senha VARCHAR(20) NOT NULL
);
GO

CREATE TABLE COMUM (
  idComum TINYINT PRIMARY KEY IDENTITY(1,1),
  playlist VARCHAR(50)
);
GO

CREATE TABLE ADMINISTRADOR (
  idAdministrador TINYINT PRIMARY KEY IDENTITY(1,1),
  idGerenciamento TINYINT FOREIGN KEY REFERENCES GERENCIAMENTO(idGerenciamento),
  playlistAdm VARCHAR(50)
);
GO

CREATE TABLE THELOGIN (
  idLogin INT PRIMARY KEY IDENTITY(1,1),
  idComum TINYINT FOREIGN KEY REFERENCES COMUM(idComum),
  idAdministrador TINYINT FOREIGN KEY REFERENCES ADMINISTRADOR(idAdministrador),
  idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
  verifyEmail VARCHAR(50) NOT NULL,
  verifySenha VARCHAR(20) NOT NULL
);
GO